export enum TicketCategory {
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  NETWORK_ADMIN = 'NETWORK_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  DATABASE_ADMIN = 'DATABASE_ADMIN',
  BUSINESS_ANALYST = 'BUSINESS_ANALYST',
  ICT_SUPPORT = 'ICT_SUPPORT',
}
